USE customer_behavior;
SHOW TABLES;

-- Q1: What is the total revenue generated by male vs. female customer?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Q2: Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );
-- Q3: Which are the top 5 products with the highestaverage review rating?
SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

  -- Q4: Compare the average Purchase amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare averge spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) AS number_of_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6: Which 5 product have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    FORMAT(
        FLOOR(
            100 * SUM(CASE
                          WHEN discount_applied = 'Yes' THEN 1
                          ELSE 0
                      END) / COUNT(*)
        ),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY FLOOR(
    100 * SUM(CASE
                  WHEN discount_applied = 'Yes' THEN 1
                  ELSE 0
              END) / COUNT(*)
) DESC
LIMIT 5;

-- Q7: Segment customer into New, Returning, and Loyal based on their
-- total number of previous purchases, and show the count of each segment.
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS segments
GROUP BY customer_segment
ORDER BY
    CASE customer_segment
        WHEN 'New' THEN 1
        WHEN 'Returning' THEN 2
        WHEN 'Loyal' THEN 3
    END;

-- Q8: What are the top 3 most purchased products within each category?
SELECT
    item_rank,
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9: Are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10: What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;